### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by pdietl** [acosmith/Saleae_CAN-FD_Analyser#1]
Hi there! Are you able to provide some build instructions for Windows? I was able to build it in Linux, but I am not very familiar with building on Windows.

**Comment by acosmith** [comment]
Hello pdietl. The code will build under any recent version of MS Visual Studio. I originally created the project using VS2017, and I know it also builds with VS2019.

Grab the Legacy 1.1.14 release of the Saleae SDK which you can find here....
https://support.saleae.com/saleae-api-and-sdk/protocol-analyzer-sdk

....and read the User guide for setting up a project in Visual Studio. These are the steps you need to take with these code files to make VS build the .dll.

Hope that helps.
