### ISSUE TITLE
Crash on different values for header and data bit rate

### ISSUE THREAD

**Issue by pdietl** [acosmith/Saleae_CAN-FD_Analyser#3]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/10335942/160952812-d2d6e822-9aba-45c9-a08c-2d25c117e87f.png">

<img width="382" alt="image" src="https://user-images.githubusercontent.com/10335942/160952845-65e46cd1-5dcf-486d-a09d-1a1f2eff78c0.png">

Something gets out of range

**Comment by acosmith** [comment]
Hello pdietl - Which version of Logic are you using? They have changed the way low level analysers are built and integrated into the Logic program recently.

Until I have time to change the code, I'm sticking with a previous version of the program for now.
